services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: "no"  # Нет необходимости в постоянном запуске
    environment:
      - NODE_ENV=production
    volumes:
      - frontend_build:/app/build

  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - frontend_build:/usr/share/nginx/html  # Используем собранные файлы фронтенда
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres_data:
  frontend_build: