services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    image: annakharatova/partners-map:latest
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend

volumes:
  static_value:
  media_value:
  postgres_data:
