# Generated by Django 5.0.6 on 2024-09-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='materials/')),
            ],
        ),
        migrations.CreateModel(
            name='RepairKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('special_feature', models.CharField(blank=True, max_length=255, null=True)),
                ('material_properties', models.TextField(blank=True, null=True)),
                ('is_hit', models.BooleanField(default=False)),
                ('engine_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_kits', to='catalog.enginecat')),
                ('groups', models.ManyToManyField(blank=True, related_name='repair_kits', to='catalog.group')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_kits', to='catalog.material')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('special_feature', models.CharField(blank=True, max_length=255, null=True)),
                ('material_properties', models.TextField(blank=True, null=True)),
                ('is_hit', models.BooleanField(default=False)),
                ('engine_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='catalog.enginecat')),
                ('groups', models.ManyToManyField(blank=True, related_name='spare_parts', to='catalog.group')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='catalog.material')),
            ],
        ),
        migrations.CreateModel(
            name='RepairKitPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('repair_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.repairkit')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sparepart')),
            ],
            options={
                'unique_together': {('repair_kit', 'spare_part')},
            },
        ),
        migrations.AddField(
            model_name='repairkit',
            name='parts',
            field=models.ManyToManyField(related_name='repair_kits', through='catalog.RepairKitPart', to='catalog.sparepart'),
        ),
        migrations.CreateModel(
            name='SparePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spare_parts/')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.sparepart')),
            ],
        ),
    ]
