name: Stroymash Workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:

  build_and_push_backend_to_docker_hub:
    name: Pushing backend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

  pull_frontend_from_docker_hub:
    name: Pulling frontend image from Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Pull frontend image
        run: docker pull annakharatova/partners-map:latest


  deploy:
    name: Deploying on remote server
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend_to_docker_hub
      - pull_frontend_from_docker_hub
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            # Переход в директорию с docker-compose.yaml
            cd /root/str
            echo "Current directory: $(pwd)"

            # Проверка наличия файла docker-compose.yaml
            if [ ! -f docker-compose.yaml ]; then
              echo "docker-compose.yaml not found!"
              exit 1
            fi

            echo "docker-compose.yaml found."
            echo "Listing files in /root/str:"
            ls -al

            # Проверим синтаксис файла docker-compose.yaml
            sudo docker compose -f docker-compose.yaml config
            if [ $? -ne 0 ]; then
              echo "Syntax error in docker-compose.yaml."
              exit 1
            fi

            # Убедимся, что .env файл создается правильно
            sudo rm -f .env
            sudo touch .env
            sudo chmod 666 .env

            echo SECRET_KEY=${{ secrets.SECRET_KEY }} | sudo tee -a .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} | sudo tee -a .env
            echo DB_NAME=${{ secrets.DB_NAME }} | sudo tee -a .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} | sudo tee -a .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} | sudo tee -a .env
            echo DB_HOST=${{ secrets.DB_HOST }} | sudo tee -a .env
            echo DB_PORT=${{ secrets.DB_PORT }} | sudo tee -a .env

            echo "Contents of .env:"
            cat .env

            # Используем полный путь к файлу docker-compose.yaml
            sudo docker compose -f /root/str/docker-compose.yaml stop
            sudo docker compose -f /root/str/docker-compose.yaml rm -f backend
            sudo docker compose -f /root/str/docker-compose.yaml pull backend
            sudo docker compose -f /root/str/docker-compose.yaml rm -f frontend
            sudo docker compose -f /root/str/docker-compose.yaml pull frontend
            sudo docker compose -f /root/str/docker-compose.yaml up -d --build
