name: Stroymash Workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:

  build_and_push_backend_to_docker_hub:
    name: Pushing backend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    name: Deploying on remote server
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend_to_docker_hub
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            # Переход в директорию с docker-compose.yml
            cd /root/str
            echo "Current directory: $(pwd)"

            # Проверка наличия файла docker-compose.yml
            if [ ! -f docker-compose.yml ]; then
              echo "docker-compose.yml not found!"
              exit 1
            fi

            echo "docker-compose.yml found."
            echo "Listing files in /root/str:"
            ls -al

            # Проверим синтаксис файла docker-compose.yml
            sudo docker compose -f docker-compose.yml config
            if [ $? -ne 0 ]; then
              echo "Syntax error in docker-compose.yml."
              exit 1
            fi

            # Создаем файл .env с переменными окружения
            sudo rm -f .env
            sudo touch .env
            sudo chmod 666 .env

            echo SECRET_KEY=${{ secrets.SECRET_KEY }} | sudo tee -a .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} | sudo tee -a .env
            echo DB_NAME=${{ secrets.DB_NAME }} | sudo tee -a .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} | sudo tee -a .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} | sudo tee -a .env
            echo DB_HOST=${{ secrets.DB_HOST }} | sudo tee -a .env
            echo DB_PORT=${{ secrets.DB_PORT }} | sudo tee -a .env

            echo "Contents of .env:"
            cat .env

            # Остановка и удаление существующих контейнеров
            sudo docker compose down

            # Пул актуальных образов
            sudo docker compose pull web

            # Сборка образа Nginx с обновленным фронтендом
            sudo docker compose build --no-cache nginx

            # Запуск сервисов
            sudo docker compose up -d
