name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Копируем docker-compose.yml на сервер
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "docker-compose.yml"
          target: "/root/str/"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}

      # Копируем папку nginx на сервер
      - name: Copy nginx directory to server
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "nginx"
          target: "/root/str/nginx"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}

      # Выполнение команд на сервере для деплоя
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переход в директорию проекта
            cd /root/str
            echo "Current directory: $(pwd)"
            echo "Listing files in $(pwd):"
            ls -la

            # Проверка наличия docker-compose.yml
            if [ ! -f docker-compose.yml ]; then
              echo "docker-compose.yml not found!"
              exit 1
            fi
            echo "docker-compose.yml found."

            # Проверка наличия nginx/nginx.Dockerfile
            if [ ! -f nginx/nginx.Dockerfile ]; then
              echo "nginx/nginx.Dockerfile not found!"
              exit 1
            fi
            echo "nginx/nginx.Dockerfile found."

            # Создание файла .env с переменными окружения
            rm -f .env
            touch .env
            chmod 600 .env

            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env

            echo "Contents of .env:"
            cat .env

            # Запуск docker-compose
            docker-compose pull
            docker-compose up -d --build
